export const SETADDRESS = "SETADDRESS";

// These are for the login and signup process
export const SETVERIFICATION = "SETVERIFICATION";
export const SETUSERAUTHENTICATIONEMAIL = "SETUSERAUTHENTICATIONEMAIL";
export const SETUSERAUTHENTICATIONUSERNAME = "SETUSERAUTHENTICATIONUSERNAME";
export const SETUSERAUTHENTICATIONPHONENUMBER = "SETUSERAUTHENTICATIONPHONENUMBER";
export const SETUSERAUTHENTICATIONPASSWORD = "SETUSERAUTHENTICATIONPASSWORD";
export const SETUSERAUTHENTICATIONPASSWORDCONFIRMATION = "SETUSERAUTHENTICATIONPASSWORDCONFIRMATION";

// These are for fecthing products and chosen products
export const SETCATEGORYPRODUCTS = "SETCATEGORYPRODUCTS";
export const SETSEARCHEDCATEGORYPRODUCTS = "SETSEARCHEDCATEGORYPRODUCTS";
export const SETCHOSENBRANDSPRODUCTS = "SETCHOSENBRANDSPRODUCTS";
export const SETEXISTINGPRODUCTS = "SETEXISTINGPRODUCTS";
export const SETCHOSENPRODUCT = "SETCHOSENPRODUCT";
export const SETLOADING = "SETLOADING";

// These are for choosing products
export const ADDTOCARTTHEITEM = "ADDTOCARTTHEITEM";
export const SUBTRACTTOCARTTHEITEM = "SUBTRACTTOCARTTHEITEM";
export const DELETETHECARTTHEITEM = "DELETETHECARTTHEITEM";
export const GIVETHEAMOUNTOFITEM = "GIVETHEAMOUNTOFITEM";

//This is for profile properties
export const SETPROFILEPROPERTIES = "SETPROFILEPROPERTIES";
export const SETPROFILEUSERNAME = "SETPROFILEUSERNAME";
export const SETPROFILEEMAIL = "SETPROFILEEMAIL";
export const SETUSERPHONE = "SETUSERPHONE";
export const SETUSERADDRESS = "SETUSERADDRESS";
